version: 2

jobs:
  build_and_test:

    machine:
      enabled: true
      image: ubuntu-1604:201903-01

    steps:
      - checkout

      - run:
          name: Fix CircleCI files permissons
          command: |
            sudo chown ubuntu:ubuntu -R *
            sudo chown ubuntu:ubuntu -R .[!.]*

      - run:
          name: Install Falcon distribution
          command: make install
          no_output_timeout: 20m

      - run:
          name: Add Falcon hosts into /etc/hosts
          command: |
            echo 127.0.0.1 frontend.docker.localhost | sudo tee -a /etc/hosts
            echo 127.0.0.1 admin.docker.localhost | sudo tee -a /etc/hosts

      - run:
          name: Make a simple check that the backend is ready and showing the log in form
          command: docker-compose run --rm php curl http://admin.docker.localhost | grep "Log in"

      - run:
          name: Make a simple check that the frontend is ready and showing the log in form
          # TODO
          command: docker-compose run --rm php curl http://frontnend.docker.localhost | grep "Log in"


workflows:
  version: 2

  build_and_test:
    jobs:
      - build_and_test
