version: "3"

services:

  node:
    image: wodby/node:$NODE_TAG
    container_name: "${PROJECT_NAME}_node"
    working_dir: /frontend
    environment:
      DEBUG: $NODE_DEBUG
      ENVIRONMENT: $ENVIRONMENT
      FRONTEND_URL: $FRONTEND_URL
      BACKEND_URL: $BACKEND_URL
      CONSUMER_ID: $CONSUMER_ID
      PAYMENT_SECRET_HEADER_NAME: $PAYMENT_SECRET_HEADER_NAME
      HTTP_AUTH_USER: $HTTP_AUTH_USER
      HTTP_AUTH_PASS: $HTTP_AUTH_PASS
    labels:
      - 'traefik.backend=node'
      - 'traefik.port=3000'
      - 'traefik.frontend.rule=Host:${FRONTEND_HOST}'
    expose:
      - "3000"
    command: yarn start:dev

  mariadb:
    image: wodby/mariadb:$MARIADB_TAG
    container_name: "${PROJECT_NAME}_mariadb"
    stop_grace_period: 30s
    environment:
      MYSQL_ROOT_PASSWORD: $DB_ROOT_PASSWORD
      MYSQL_DATABASE: $DB_NAME
      MYSQL_USER: $DB_USER
      MYSQL_PASSWORD: $DB_PASSWORD

  php:
    image: wodby/drupal-php:$PHP_TAG
    container_name: "${PROJECT_NAME}_php"
    environment:
      PHP_SENDMAIL_PATH: /usr/sbin/sendmail -t -i -S mailhog:1025
      DB_HOST: $DB_HOST
      DB_USER: $DB_USER
      DB_PASSWORD: $DB_PASSWORD
      DB_NAME: $DB_NAME
      DB_DRIVER: $DB_DRIVER
      COLUMNS: 80 # Set 80 columns for docker exec -it.
      ENVIRONMENT: $ENVIRONMENT
      TEST_USERS_PASSWORD: $TEST_USERS_PASSWORD
      PAYMENT_SECRET_HEADER_NAME: $PAYMENT_SECRET_HEADER_NAME
      PAYMENT_SECRET_HEADER_VALUE: $PAYMENT_SECRET_HEADER_VALUE
      HTTP_AUTH_USER: $HTTP_AUTH_USER
      HTTP_AUTH_PASS: $HTTP_AUTH_PASS

  nginx:
    image: wodby/nginx:$NGINX_TAG
    container_name: "${PROJECT_NAME}_nginx"
    depends_on:
      - php
    environment:
      NGINX_STATIC_OPEN_FILE_CACHE: "off"
      NGINX_ERROR_LOG_LEVEL: debug
      NGINX_BACKEND_HOST: php
      NGINX_SERVER_ROOT: /var/www/html/web
      NGINX_VHOST_PRESET: drupal8
    labels:
      - 'traefik.backend=nginx'
      - 'traefik.port=80'
      - 'traefik.frontend.rule=Host:${BACKEND_HOST}'

  mailhog:
    image: mailhog/mailhog
    container_name: "${PROJECT_NAME}_mailhog"
    labels:
      - 'traefik.backend=mailhog'
      - 'traefik.port=8025'
      - 'traefik.frontend.rule=Host:mailhog.${PROJECT_BASE_URL}'

  traefik:
    image: $TRAEFIK_IMAGE:$TRAEFIK_TAG
    container_name: "${PROJECT_NAME}_traefik"
    command: -c /dev/null --web --docker --logLevel=INFO
    ports:
      - '80:80'
      - '443:443'
      - '8080:8080' # Dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      default:
        aliases:
          - ${BACKEND_HOST}
          - ${FRONTEND_HOST}
